P8105 Homework 2
================
Astrid Xu
2026-10-06

# Question 1

``` r
subway =
  read_csv("data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") |>
  janitor::clean_names() |>
  select(
    line, station_name, station_latitude, station_longitude,
    route1:route11,
    entry, vending, entrance_type, ada)
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
subway
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <chr>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

``` r
subway =
  subway |>
  mutate(
    entry = ifelse(entry == "YES", TRUE, FALSE))
subway
```

    ## # A tibble: 1,868 × 19
    ##    line     station_name station_latitude station_longitude route1 route2 route3
    ##    <chr>    <chr>                   <dbl>             <dbl> <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  2 4 Avenue 25th St                  40.7             -74.0 R      <NA>   <NA>  
    ##  3 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  4 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  5 4 Avenue 36th St                  40.7             -74.0 N      R      <NA>  
    ##  6 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  7 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  8 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ##  9 4 Avenue 45th St                  40.6             -74.0 R      <NA>   <NA>  
    ## 10 4 Avenue 53rd St                  40.6             -74.0 R      <NA>   <NA>  
    ## # ℹ 1,858 more rows
    ## # ℹ 12 more variables: route4 <chr>, route5 <chr>, route6 <chr>, route7 <chr>,
    ## #   route8 <dbl>, route9 <dbl>, route10 <dbl>, route11 <dbl>, entry <lgl>,
    ## #   vending <chr>, entrance_type <chr>, ada <lgl>

``` r
# Could also use case_match
# mutate(
#  entry = case_match(
#    entry,
#    "YES" ~ TRUE,
#    "NO" ~ FALSE
# ))
```

After cleaning, there are 1868 observations and 19 variables in the
dataset. The dataset contains information about subway lines, station
names, station locations (latitude and longitude), routes served,
whether entrances allow entry, vending availability, entrance types, and
ADA compliance. For the data cleaning steps, I first imported the
dataset using read_csv() and cleaned all variable names using
clean_names(). The original dataset contained 32 variables in total, so
I used select() to retain only the required variables and saved the
cleaned dataset as subway. I then checked the dataset to make sure that
it satisfied the requirements. Next I used mutate() to modify the
existing entry variable. I am more familiar with ifelse(), it means if
the observation equals to YES, then convert it to TURE. If else other
than YES, then convert it to FALSE. I viewed the subway dataset again to
check the result. The resulting dataset is not tidy because route
information is stored across multiple variables (route1 through route11)
instead of having route number and route name as distinct variables.

``` r
subway |>
  distinct(line, station_name)
```

    ## # A tibble: 465 × 2
    ##    line     station_name            
    ##    <chr>    <chr>                   
    ##  1 4 Avenue 25th St                 
    ##  2 4 Avenue 36th St                 
    ##  3 4 Avenue 45th St                 
    ##  4 4 Avenue 53rd St                 
    ##  5 4 Avenue 59th St                 
    ##  6 4 Avenue 77th St                 
    ##  7 4 Avenue 86th St                 
    ##  8 4 Avenue 95th St                 
    ##  9 4 Avenue 9th St                  
    ## 10 4 Avenue Atlantic Av-Barclays Ctr
    ## # ℹ 455 more rows

There are 465 distinct stations.

``` r
subway |>
  filter(ada == TRUE) |>
  count(line, station_name)
```

    ## # A tibble: 84 × 3
    ##    line            station_name                       n
    ##    <chr>           <chr>                          <int>
    ##  1 4 Avenue        Atlantic Av-Barclays Ctr           1
    ##  2 4 Avenue        DeKalb Av                          6
    ##  3 4 Avenue        Pacific St                         2
    ##  4 42nd St Shuttle Grand Central                      7
    ##  5 6 Avenue        34th St                           10
    ##  6 6 Avenue        47-50th Sts Rockefeller Center    17
    ##  7 6 Avenue        Church Av                          6
    ##  8 63rd Street     21st St                            5
    ##  9 63rd Street     Lexington Av                       5
    ## 10 63rd Street     Roosevelt Island                   1
    ## # ℹ 74 more rows

Only 84 stations are ADA compliant.

``` r
no_vending_entry =
  subway |>
  filter(vending == "NO", entry == TRUE)

no_vending =
  subway |>
  filter(vending == "NO")

nrow(no_vending_entry) / nrow(no_vending)
```

    ## [1] 0.3770492

The proportion of station entrances / exits without vending allow
entrance is 0.3770.

``` r
# Reformat can't be proceeded, cuz the variable type of routes doesn't match. So fix the variable types first
str(subway)
```

    ## tibble [1,868 × 19] (S3: tbl_df/tbl/data.frame)
    ##  $ line             : chr [1:1868] "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ station_name     : chr [1:1868] "25th St" "25th St" "36th St" "36th St" ...
    ##  $ station_latitude : num [1:1868] 40.7 40.7 40.7 40.7 40.7 ...
    ##  $ station_longitude: num [1:1868] -74 -74 -74 -74 -74 ...
    ##  $ route1           : chr [1:1868] "R" "R" "N" "N" ...
    ##  $ route2           : chr [1:1868] NA NA "R" "R" ...
    ##  $ route3           : chr [1:1868] NA NA NA NA ...
    ##  $ route4           : chr [1:1868] NA NA NA NA ...
    ##  $ route5           : chr [1:1868] NA NA NA NA ...
    ##  $ route6           : chr [1:1868] NA NA NA NA ...
    ##  $ route7           : chr [1:1868] NA NA NA NA ...
    ##  $ route8           : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route9           : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route10          : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ route11          : num [1:1868] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ entry            : logi [1:1868] TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ vending          : chr [1:1868] "YES" "YES" "YES" "YES" ...
    ##  $ entrance_type    : chr [1:1868] "Stair" "Stair" "Stair" "Stair" ...
    ##  $ ada              : logi [1:1868] FALSE FALSE FALSE FALSE FALSE FALSE ...

``` r
subway =
  subway |>
  mutate(
    route8 = as.character(route8),
    route9 = as.character(route9),
    route10 = as.character(route10),
    route11 = as.character(route11)
  )
str(subway)
```

    ## tibble [1,868 × 19] (S3: tbl_df/tbl/data.frame)
    ##  $ line             : chr [1:1868] "4 Avenue" "4 Avenue" "4 Avenue" "4 Avenue" ...
    ##  $ station_name     : chr [1:1868] "25th St" "25th St" "36th St" "36th St" ...
    ##  $ station_latitude : num [1:1868] 40.7 40.7 40.7 40.7 40.7 ...
    ##  $ station_longitude: num [1:1868] -74 -74 -74 -74 -74 ...
    ##  $ route1           : chr [1:1868] "R" "R" "N" "N" ...
    ##  $ route2           : chr [1:1868] NA NA "R" "R" ...
    ##  $ route3           : chr [1:1868] NA NA NA NA ...
    ##  $ route4           : chr [1:1868] NA NA NA NA ...
    ##  $ route5           : chr [1:1868] NA NA NA NA ...
    ##  $ route6           : chr [1:1868] NA NA NA NA ...
    ##  $ route7           : chr [1:1868] NA NA NA NA ...
    ##  $ route8           : chr [1:1868] NA NA NA NA ...
    ##  $ route9           : chr [1:1868] NA NA NA NA ...
    ##  $ route10          : chr [1:1868] NA NA NA NA ...
    ##  $ route11          : chr [1:1868] NA NA NA NA ...
    ##  $ entry            : logi [1:1868] TRUE TRUE TRUE TRUE TRUE TRUE ...
    ##  $ vending          : chr [1:1868] "YES" "YES" "YES" "YES" ...
    ##  $ entrance_type    : chr [1:1868] "Stair" "Stair" "Stair" "Stair" ...
    ##  $ ada              : logi [1:1868] FALSE FALSE FALSE FALSE FALSE FALSE ...

``` r
subway_reform =
  subway |>
  pivot_longer(route1:route11,
    names_to = "route_number",
    values_to = "route_name")
subway_reform
```

    ## # A tibble: 20,548 × 10
    ##    line     station_name station_latitude station_longitude entry vending
    ##    <chr>    <chr>                   <dbl>             <dbl> <lgl> <chr>  
    ##  1 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  2 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  3 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  4 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  5 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  6 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  7 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  8 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ##  9 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## 10 4 Avenue 25th St                  40.7             -74.0 TRUE  YES    
    ## # ℹ 20,538 more rows
    ## # ℹ 4 more variables: entrance_type <chr>, ada <lgl>, route_number <chr>,
    ## #   route_name <chr>

``` r
A_train =
  subway_reform |>
  filter(route_name == "A") |>
  distinct(line, station_name)
A_train
```

    ## # A tibble: 60 × 2
    ##    line            station_name                 
    ##    <chr>           <chr>                        
    ##  1 42nd St Shuttle Times Square                 
    ##  2 8 Avenue        125th St                     
    ##  3 8 Avenue        145th St                     
    ##  4 8 Avenue        14th St                      
    ##  5 8 Avenue        168th St - Washington Heights
    ##  6 8 Avenue        175th St                     
    ##  7 8 Avenue        181st St                     
    ##  8 8 Avenue        190th St                     
    ##  9 8 Avenue        34th St                      
    ## 10 8 Avenue        42nd St                      
    ## # ℹ 50 more rows

``` r
A_train_ada =
  subway_reform |>
  filter(route_name == "A", ada == TRUE) |>
  distinct(line, station_name)
A_train_ada
```

    ## # A tibble: 17 × 2
    ##    line             station_name                 
    ##    <chr>            <chr>                        
    ##  1 8 Avenue         14th St                      
    ##  2 8 Avenue         168th St - Washington Heights
    ##  3 8 Avenue         175th St                     
    ##  4 8 Avenue         34th St                      
    ##  5 8 Avenue         42nd St                      
    ##  6 8 Avenue         59th St                      
    ##  7 8 Avenue         Inwood - 207th St            
    ##  8 8 Avenue         West 4th St                  
    ##  9 8 Avenue         World Trade Center           
    ## 10 Broadway         Times Square-42nd St         
    ## 11 Broadway-7th Ave 59th St-Columbus Circle      
    ## 12 Broadway-7th Ave Times Square                 
    ## 13 Canarsie         8th Av                       
    ## 14 Franklin         Franklin Av                  
    ## 15 Fulton           Euclid Av                    
    ## 16 Fulton           Franklin Av                  
    ## 17 Rockaway         Howard Beach

60 distinct stations serve the A train. Of those stations that serve the
A train, only 17 are ADA compliant.

# Question 2

``` r
trash =
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N742"
  )
trash
```

    ## # A tibble: 740 × 14
    ##    Dumpster Month Year  Date                `Weight (tons)`
    ##       <dbl> <chr> <chr> <dttm>                        <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00            4.31
    ##  2        2 May   2014  2014-05-16 00:00:00            2.74
    ##  3        3 May   2014  2014-05-16 00:00:00            3.45
    ##  4        4 May   2014  2014-05-17 00:00:00            3.1 
    ##  5        5 May   2014  2014-05-17 00:00:00            4.06
    ##  6        6 May   2014  2014-05-20 00:00:00            2.71
    ##  7        7 May   2014  2014-05-21 00:00:00            1.91
    ##  8        8 May   2014  2014-05-28 00:00:00            3.7 
    ##  9        9 June  2014  2014-06-05 00:00:00            2.52
    ## 10       10 June  2014  2014-06-11 00:00:00            3.76
    ## # ℹ 730 more rows
    ## # ℹ 9 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Sports Balls` <dbl>,
    ## #   `Homes Powered*` <dbl>

``` r
trash =
  trash |>
  janitor::clean_names()
names(trash)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "plastic_bags"       "wrappers"          
    ## [13] "sports_balls"       "homes_powered"

``` r
trash =
  trash |>
  mutate(
    sports_balls = round(sports_balls),
    sports_balls = as.integer(sports_balls)
  )
trash
```

    ## # A tibble: 740 × 14
    ##    dumpster month year  date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <chr> <dttm>                    <dbl>              <dbl>
    ##  1        1 May   2014  2014-05-16 00:00:00        4.31                 18
    ##  2        2 May   2014  2014-05-16 00:00:00        2.74                 13
    ##  3        3 May   2014  2014-05-16 00:00:00        3.45                 15
    ##  4        4 May   2014  2014-05-17 00:00:00        3.1                  15
    ##  5        5 May   2014  2014-05-17 00:00:00        4.06                 18
    ##  6        6 May   2014  2014-05-20 00:00:00        2.71                 13
    ##  7        7 May   2014  2014-05-21 00:00:00        1.91                  8
    ##  8        8 May   2014  2014-05-28 00:00:00        3.7                  16
    ##  9        9 June  2014  2014-06-05 00:00:00        2.52                 14
    ## 10       10 June  2014  2014-06-11 00:00:00        3.76                 18
    ## # ℹ 730 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>

``` r
str(trash)
```

    ## tibble [740 × 14] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:740] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:740] "May" "May" "May" "May" ...
    ##  $ year              : chr [1:740] "2014" "2014" "2014" "2014" ...
    ##  $ date              : POSIXct[1:740], format: "2014-05-16" "2014-05-16" ...
    ##  $ weight_tons       : num [1:740] 4.31 2.74 3.45 3.1 4.06 2.71 1.91 3.7 2.52 3.76 ...
    ##  $ volume_cubic_yards: num [1:740] 18 13 15 15 18 13 8 16 14 18 ...
    ##  $ plastic_bottles   : num [1:740] 1450 1120 2450 2380 980 1430 910 3580 2400 1340 ...
    ##  $ polystyrene       : num [1:740] 1820 1030 3100 2730 870 2140 1090 4310 2790 1730 ...
    ##  $ cigarette_butts   : num [1:740] 126000 91000 105000 100000 120000 90000 56000 112000 98000 130000 ...
    ##  $ glass_bottles     : num [1:740] 72 42 50 52 72 46 32 58 49 75 ...
    ##  $ plastic_bags      : num [1:740] 584 496 1080 896 368 ...
    ##  $ wrappers          : num [1:740] 1162 874 2032 1971 753 ...
    ##  $ sports_balls      : int [1:740] 7 5 6 6 7 5 3 6 6 7 ...
    ##  $ homes_powered     : num [1:740] 0 0 0 0 0 0 0 0 0 0 ...

``` r
professor =
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M139"
  )
professor
```

    ## # A tibble: 137 × 13
    ##    Dumpster Month     Year Date                `Weight (tons)`
    ##       <dbl> <chr>    <dbl> <dttm>                        <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00            1.79
    ##  2        2 January   2017 2017-01-30 00:00:00            1.58
    ##  3        3 February  2017 2017-02-26 00:00:00            2.32
    ##  4        4 February  2017 2017-02-26 00:00:00            3.72
    ##  5        5 February  2017 2017-02-28 00:00:00            1.45
    ##  6        6 March     2017 2017-03-30 00:00:00            1.71
    ##  7        7 April     2017 2017-04-01 00:00:00            1.82
    ##  8        8 April     2017 2017-04-20 00:00:00            2.37
    ##  9        9 May       2017 2017-05-10 00:00:00            2.64
    ## 10       10 May       2017 2017-05-26 00:00:00            2.78
    ## # ℹ 127 more rows
    ## # ℹ 8 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <chr>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Glass Bottles` <dbl>,
    ## #   `Plastic Bags` <dbl>, Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
professor =
  professor |>
  janitor::clean_names()
names(professor)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "glass_bottles"      "plastic_bags"       "wrappers"          
    ## [13] "homes_powered"

``` r
str(professor)
```

    ## tibble [137 × 13] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:137] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:137] "January" "January" "February" "February" ...
    ##  $ year              : num [1:137] 2017 2017 2017 2017 2017 ...
    ##  $ date              : POSIXct[1:137], format: "2017-01-02" "2017-01-30" ...
    ##  $ weight_tons       : num [1:137] 1.79 1.58 2.32 3.72 1.45 1.71 1.82 2.37 2.64 2.78 ...
    ##  $ volume_cubic_yards: num [1:137] 15 15 18 15 15 15 15 15 15 15 ...
    ##  $ plastic_bottles   : chr [1:137] "1950.0" "9540.0" "8350.0" "8590.0" ...
    ##  $ polystyrene       : num [1:137] 6080 11230 9210 1030 9950 ...
    ##  $ cigarette_butts   : num [1:137] 19700 17600 12000 13000 16000 14000 17000 15000 17000 13000 ...
    ##  $ glass_bottles     : num [1:137] 8 14 19 21 18 23 26 14 28 22 ...
    ##  $ plastic_bags      : num [1:137] 3100 5630 6430 5870 7450 ...
    ##  $ wrappers          : num [1:137] 15600 16700 12400 11030 15340 ...
    ##  $ homes_powered     : num [1:137] 29.8 26.3 38.7 62 24.2 ...

``` r
gwynnda =
  read_excel("data/202610 Trash Wheel Collection Data.xlsx",
    sheet = "Gwynnda the Good Wheel of the W",
    range = "A2:L394"
  )
gwynnda
```

    ## # A tibble: 392 × 12
    ##    Dumpster Month   Year Date                `Weight (tons)`
    ##       <dbl> <chr>  <dbl> <dttm>                        <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00            0.93
    ##  2        2 July    2021 2021-07-07 00:00:00            2.26
    ##  3        3 July    2021 2021-07-07 00:00:00            1.62
    ##  4        4 July    2021 2021-07-16 00:00:00            1.76
    ##  5        5 July    2021 2021-07-30 00:00:00            1.53
    ##  6        6 August  2021 2021-08-11 00:00:00            2.06
    ##  7        7 August  2021 2021-08-14 00:00:00            1.9 
    ##  8        8 August  2021 2021-08-16 00:00:00            2.16
    ##  9        9 August  2021 2021-08-16 00:00:00            2.6 
    ## 10       10 August  2021 2021-08-17 00:00:00            3.21
    ## # ℹ 382 more rows
    ## # ℹ 7 more variables: `Volume (cubic yards)` <dbl>, `Plastic Bottles` <dbl>,
    ## #   Polystyrene <dbl>, `Cigarette Butts` <dbl>, `Plastic Bags` <dbl>,
    ## #   Wrappers <dbl>, `Homes Powered*` <dbl>

``` r
gwynnda =
  gwynnda |>
  janitor::clean_names()
names(gwynnda)
```

    ##  [1] "dumpster"           "month"              "year"              
    ##  [4] "date"               "weight_tons"        "volume_cubic_yards"
    ##  [7] "plastic_bottles"    "polystyrene"        "cigarette_butts"   
    ## [10] "plastic_bags"       "wrappers"           "homes_powered"

``` r
str(gwynnda)
```

    ## tibble [392 × 12] (S3: tbl_df/tbl/data.frame)
    ##  $ dumpster          : num [1:392] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ month             : chr [1:392] "July" "July" "July" "July" ...
    ##  $ year              : num [1:392] 2021 2021 2021 2021 2021 ...
    ##  $ date              : POSIXct[1:392], format: "2021-07-03" "2021-07-07" ...
    ##  $ weight_tons       : num [1:392] 0.93 2.26 1.62 1.76 1.53 2.06 1.9 2.16 2.6 3.21 ...
    ##  $ volume_cubic_yards: num [1:392] 15 15 15 15 15 15 15 15 15 15 ...
    ##  $ plastic_bottles   : num [1:392] 1200 2000 1800 1000 2100 2400 2700 3000 980 240 ...
    ##  $ polystyrene       : num [1:392] 360 240 270 180 240 360 320 320 180 42 ...
    ##  $ cigarette_butts   : num [1:392] 3400 3900 2900 2100 4000 3900 4200 4000 1800 400 ...
    ##  $ plastic_bags      : num [1:392] 1800 2200 2400 1800 2700 3000 3200 3600 1000 360 ...
    ##  $ wrappers          : num [1:392] NA NA NA NA NA NA NA NA NA NA ...
    ##  $ homes_powered     : num [1:392] 15.5 37.7 27 29.3 25.5 ...

``` r
trash =
  trash |>
  mutate(
    trash_wheel = "Mr. Trash Wheel"
  )

professor =
  professor |>
  mutate(
    trash_wheel = "Professor Trash Wheel"
  )

gwynnda =
  gwynnda |>
  mutate(
    trash_wheel = "Gwynnda"
  )

# Combination can't be proceeded, cuz year and plastic_bottles have two different variable types (chr&dbl), so need to fix them first
trash =
  trash |>
  mutate(
    year = as.numeric(year)
  )

professor |>
  filter(plastic_bottles == "dive")
```

    ## # A tibble: 1 × 14
    ##   dumpster month     year date                weight_tons volume_cubic_yards
    ##      <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ## 1      135 November  2025 2025-11-13 00:00:00        1.55                  6
    ## # ℹ 8 more variables: plastic_bottles <chr>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

``` r
professor =
  professor |>
  mutate(
    plastic_bottles = ifelse(plastic_bottles == "dive", NA, plastic_bottles),
    plastic_bottles = as.numeric(plastic_bottles)
  )
professor
```

    ## # A tibble: 137 × 14
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 127 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, trash_wheel <chr>

``` r
trash_combined =
  bind_rows(trash, professor, gwynnda)
trash_combined
```

    ## # A tibble: 1,269 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 1,259 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <int>, homes_powered <dbl>, trash_wheel <chr>

The merged dataset contains 1,269 observations and 15 variables. It
tells key information including the name of the garbage truck, the trash
can number, the month, year, and date of collection, as well as the
weight and volume of the collected trash. The dataset also provides the
specific types of trash collected, such as plastic bottles, cigarette
butts, plastic bags, and wrapping paper.

``` r
professor_total =
  trash_combined |>
  filter(trash_wheel == "Professor Trash Wheel")

professor_total |>
  summarize(
    total_weight = sum(weight_tons)
  )
```

    ## # A tibble: 1 × 1
    ##   total_weight
    ##          <dbl>
    ## 1         295.

The total weight of trash collected by Professor Trash Wheel was 295
tons.

``` r
gwynnda_june_total =
  trash_combined |>
  filter(
    trash_wheel == "Gwynnda",
    year == 2022,
    month == "June"
  )

gwynnda_june_total |>
  summarize(
    total_cigarette_butts = sum(cigarette_butts)
  )
```

    ## # A tibble: 1 × 1
    ##   total_cigarette_butts
    ##                   <dbl>
    ## 1                 18120

The total number of cigarette butts collected by Gwynnda in June 2022
was 18,120.

# Question 3

``` r
baseline =
  read_csv(
    "data/MCI_baseline.csv",
    skip = 1
  )
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
baseline
```

    ## # A tibble: 483 × 6
    ##       ID `Current Age`   Sex Education apoe4 `Age at onset`
    ##    <dbl>         <dbl> <dbl>     <dbl> <dbl> <chr>         
    ##  1     1          63.1     0        16     1 .             
    ##  2     2          65.6     0        20     1 .             
    ##  3     3          62.5     1        16     1 66.8          
    ##  4     4          69.8     0        16     0 .             
    ##  5     5          66       1        16     0 68.7          
    ##  6     6          62.5     1        16     0 .             
    ##  7     7          66.5     1        18     0 74            
    ##  8     8          67.2     0        18     0 .             
    ##  9     9          66.7     0        16     0 .             
    ## 10    10          64.1     0        18     0 .             
    ## # ℹ 473 more rows

``` r
baseline =
  baseline |>
  janitor::clean_names()
names(baseline)
```

    ## [1] "id"           "current_age"  "sex"          "education"    "apoe4"       
    ## [6] "age_at_onset"

``` r
baseline =
  baseline |>
  mutate(
    sex = case_match(
      sex,
      1 ~ "Male",
      0 ~ "Female"
    ),
    apoe4 = case_match(
      apoe4,
      1 ~ "Carrier",
      0 ~ "Non-carrier"
    )
  )
```

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `sex = case_match(sex, 1 ~ "Male", 0 ~ "Female")`.
    ## Caused by warning:
    ## ! `case_match()` was deprecated in dplyr 1.2.0.
    ## ℹ Please use `recode_values()` instead.

``` r
baseline
```

    ## # A tibble: 483 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>       <chr>       
    ##  1     1        63.1 Female        16 Carrier     .           
    ##  2     2        65.6 Female        20 Carrier     .           
    ##  3     3        62.5 Male          16 Carrier     66.8        
    ##  4     4        69.8 Female        16 Non-carrier .           
    ##  5     5        66   Male          16 Non-carrier 68.7        
    ##  6     6        62.5 Male          16 Non-carrier .           
    ##  7     7        66.5 Male          18 Non-carrier 74          
    ##  8     8        67.2 Female        18 Non-carrier .           
    ##  9     9        66.7 Female        16 Non-carrier .           
    ## 10    10        64.1 Female        18 Non-carrier .           
    ## # ℹ 473 more rows

``` r
baseline =
  baseline |>
  mutate(
    age_at_onset = na_if(age_at_onset, "."),
    age_at_onset = as.numeric(age_at_onset)
  )
baseline
```

    ## # A tibble: 483 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ##  1     1        63.1 Female        16 Carrier             NA  
    ##  2     2        65.6 Female        20 Carrier             NA  
    ##  3     3        62.5 Male          16 Carrier             66.8
    ##  4     4        69.8 Female        16 Non-carrier         NA  
    ##  5     5        66   Male          16 Non-carrier         68.7
    ##  6     6        62.5 Male          16 Non-carrier         NA  
    ##  7     7        66.5 Male          18 Non-carrier         74  
    ##  8     8        67.2 Female        18 Non-carrier         NA  
    ##  9     9        66.7 Female        16 Non-carrier         NA  
    ## 10    10        64.1 Female        18 Non-carrier         NA  
    ## # ℹ 473 more rows

After importing the dataset using read_csv(), I noticed that the first
row of the table did not contain the variable names I needed, but
instead contained descriptions of the variables. So to make R skip the
first row and recognize the second row as the variable names, I added
the skip = 1 argument when using read_csv(). Then based on the codebook,
I converted sex and APOE4 carrier status into their corresponding
categorical variables and converted missing values to NA. To remove
participants who did not meet the stated inclusion criteria (i.e., no
MCI at baseline), I first used filter() to identify participants who had
already developed MCI by the time they entered the study. After checking
these participants individually, I used filter() to retain only
participants whose current age was less than their age at MCI onset or
who did not develop MCI during the follow-up period. The original
dataset has 483 participants, resulting dataset contains 479
participants and 6 variables, including participant ID, baseline age,
sex, education, APOE4 carrier status, and age at MCI onset.

``` r
baseline |>
  filter(age_at_onset <= current_age)
```

    ## # A tibble: 4 × 6
    ##      id current_age sex    education apoe4       age_at_onset
    ##   <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ## 1    72        62.9 Male          16 Carrier             62.5
    ## 2   234        66.7 Male          18 Non-carrier         66.7
    ## 3   283        69   Male          16 Non-carrier         68.3
    ## 4   380        70.3 Female        16 Non-carrier         70.2

``` r
baseline =
  baseline |>
  filter(is.na(age_at_onset) | age_at_onset > current_age)
baseline
```

    ## # A tibble: 479 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>              <dbl>
    ##  1     1        63.1 Female        16 Carrier             NA  
    ##  2     2        65.6 Female        20 Carrier             NA  
    ##  3     3        62.5 Male          16 Carrier             66.8
    ##  4     4        69.8 Female        16 Non-carrier         NA  
    ##  5     5        66   Male          16 Non-carrier         68.7
    ##  6     6        62.5 Male          16 Non-carrier         NA  
    ##  7     7        66.5 Male          18 Non-carrier         74  
    ##  8     8        67.2 Female        18 Non-carrier         NA  
    ##  9     9        66.7 Female        16 Non-carrier         NA  
    ## 10    10        64.1 Female        18 Non-carrier         NA  
    ## # ℹ 469 more rows

``` r
developed =
  baseline |>
  filter(!is.na(age_at_onset))
nrow(developed)
```

    ## [1] 93

After excluding, 479 participants were recruited into the study. Among
them, 93 developed MCI during the follow-up period.

``` r
baseline |>
  summarize(
    average_baseline_age = mean(current_age)
  )
```

    ## # A tibble: 1 × 1
    ##   average_baseline_age
    ##                  <dbl>
    ## 1                 65.0

The average baseline age was 65.0 years.

``` r
female =
  baseline |>
  filter(sex == "Female")

female_carrier =
  baseline |>
  filter(
    sex == "Female",
    apoe4 == "Carrier"
  )

nrow(female_carrier) / nrow(female)
```

    ## [1] 0.3

Among female participants, 30% were APOE4 carriers.

``` r
amyloid =
  read_csv(
    "data/mci_amyloid.csv",
    skip = 1
  )
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
amyloid
```

    ## # A tibble: 487 × 6
    ##    `Study ID` Baseline    `Time 2`    `Time 4`    `Time 6`    `Time 8`   
    ##         <dbl> <chr>       <chr>       <chr>       <chr>       <chr>      
    ##  1          1 0.1105487   <NA>        0.109325197 0.104756131 0.107257697
    ##  2          2 0.107481183 0.109157373 0.109457839 0.105729713 0.10661845 
    ##  3          3 0.106087034 0.108744509 0.106065035 <NA>        0.106152357
    ##  4          4 0.109251358 0.108699686 0.110540386 0.107476797 0.111212209
    ##  5          5 0.107950408 0.112273883 0.115139677 0.106606054 0.106052066
    ##  6          6 0.112426974 0.112853415 0.11143945  0.110279277 0.114982747
    ##  7          7 0.112246391 <NA>        0.104251905 0.112485583 0.112055612
    ##  8          8 0.109563372 0.109470828 <NA>        0.108742168 0.110268552
    ##  9          9 0.112101884 0.109781199 0.108832888 <NA>        <NA>       
    ## 10         10 0.1116094   0.111592149 <NA>        <NA>        0.110051296
    ## # ℹ 477 more rows

``` r
amyloid =
  amyloid |>
  janitor::clean_names()
names(amyloid)
```

    ## [1] "study_id" "baseline" "time_2"   "time_4"   "time_6"   "time_8"

``` r
str(amyloid)
```

    ## spc_tbl_ [487 × 6] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
    ##  $ study_id: num [1:487] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ baseline: chr [1:487] "0.1105487" "0.107481183" "0.106087034" "0.109251358" ...
    ##  $ time_2  : chr [1:487] NA "0.109157373" "0.108744509" "0.108699686" ...
    ##  $ time_4  : chr [1:487] "0.109325197" "0.109457839" "0.106065035" "0.110540386" ...
    ##  $ time_6  : chr [1:487] "0.104756131" "0.105729713" NA "0.107476797" ...
    ##  $ time_8  : chr [1:487] "0.107257697" "0.10661845" "0.106152357" "0.111212209" ...
    ##  - attr(*, "spec")=
    ##   .. cols(
    ##   ..   `Study ID` = col_double(),
    ##   ..   Baseline = col_character(),
    ##   ..   `Time 2` = col_character(),
    ##   ..   `Time 4` = col_character(),
    ##   ..   `Time 6` = col_character(),
    ##   ..   `Time 8` = col_character()
    ##   .. )
    ##  - attr(*, "problems")=<pointer: 0x000001624dcff3e0>

``` r
amyloid |>
  filter(is.na(as.numeric(baseline)))
```

    ## Warning: There was 1 warning in `filter()`.
    ## ℹ In argument: `is.na(as.numeric(baseline))`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

    ## # A tibble: 2 × 6
    ##   study_id baseline time_2      time_4      time_6      time_8     
    ##      <dbl> <chr>    <chr>       <chr>       <chr>       <chr>      
    ## 1       73 <NA>     0.109440795 0.112072561 0.104290102 0.107973912
    ## 2      495 Na       0.105142354 0.108149625 0.105918659 0.102512562

``` r
amyloid =
  amyloid |>
  mutate(
    baseline = as.numeric(baseline),
    time_2 = as.numeric(time_2),
    time_4 = as.numeric(time_4),
    time_6 = as.numeric(time_6),
    time_8 = as.numeric(time_8)
  )
```

    ## Warning: There were 5 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `baseline = as.numeric(baseline)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.

``` r
amyloid
```

    ## # A tibble: 487 × 6
    ##    study_id baseline time_2 time_4 time_6 time_8
    ##       <dbl>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ##  1        1    0.111 NA      0.109  0.105  0.107
    ##  2        2    0.107  0.109  0.109  0.106  0.107
    ##  3        3    0.106  0.109  0.106 NA      0.106
    ##  4        4    0.109  0.109  0.111  0.107  0.111
    ##  5        5    0.108  0.112  0.115  0.107  0.106
    ##  6        6    0.112  0.113  0.111  0.110  0.115
    ##  7        7    0.112 NA      0.104  0.112  0.112
    ##  8        8    0.110  0.109 NA      0.109  0.110
    ##  9        9    0.112  0.110  0.109 NA     NA    
    ## 10       10    0.112  0.112 NA     NA      0.110
    ## # ℹ 477 more rows

``` r
str(amyloid)
```

    ## tibble [487 × 6] (S3: tbl_df/tbl/data.frame)
    ##  $ study_id: num [1:487] 1 2 3 4 5 6 7 8 9 10 ...
    ##  $ baseline: num [1:487] 0.111 0.107 0.106 0.109 0.108 ...
    ##  $ time_2  : num [1:487] NA 0.109 0.109 0.109 0.112 ...
    ##  $ time_4  : num [1:487] 0.109 0.109 0.106 0.111 0.115 ...
    ##  $ time_6  : num [1:487] 0.105 0.106 NA 0.107 0.107 ...
    ##  $ time_8  : num [1:487] 0.107 0.107 0.106 0.111 0.106 ...

``` r
amyloid =
  amyloid |>
  pivot_longer(
    baseline:time_8,
    names_to = "time",
    values_to = "amyloid"
  )
amyloid
```

    ## # A tibble: 2,435 × 3
    ##    study_id time     amyloid
    ##       <dbl> <chr>      <dbl>
    ##  1        1 baseline   0.111
    ##  2        1 time_2    NA    
    ##  3        1 time_4     0.109
    ##  4        1 time_6     0.105
    ##  5        1 time_8     0.107
    ##  6        2 baseline   0.107
    ##  7        2 time_2     0.109
    ##  8        2 time_4     0.109
    ##  9        2 time_6     0.106
    ## 10        2 time_8     0.107
    ## # ℹ 2,425 more rows

After importing the data, I noticed that the rows and variable names had
the same issue as the baseline dataset. So I again used skip = 1 in
read_csv() to skip the first row and use the second row as the variable
names. After cleaning the variable names, I noticed that the biomarker
values which should be numeric were recognized as character variables. I
suspected that this was caused by some non-numeric values in these
columns. I used is.na() with numeric conversion to identify values that
could not be converted to numbers and found that missing values were
recorded in two different ways, “NA” and “Na”. Since both represented
missing values, I directly converted all biomarker variables to numeric
values, which converted these values to NA without affecting the
available measurements. Then I used pivot_longer() to separate the five
measurement times for each participant into individual observations. The
original dataset contained 487 participants and 6 variables, with five
amyloid biomarker measurements stored in separate columns for baseline
and Times 2, 4, 6, and 8. After reformatting, the dataset contains 2,435
observations and 3 variables: participant ID, measurement time, and
amyloid biomarker value. Each row now represents one participant at one
measurement time.

``` r
amyloid =
  amyloid |>
  rename(id = study_id)

mci =
  baseline |>
  inner_join(amyloid, by = "id")
mci
```

    ## # A tibble: 2,355 × 8
    ##       id current_age sex    education apoe4   age_at_onset time     amyloid
    ##    <dbl>       <dbl> <chr>      <dbl> <chr>          <dbl> <chr>      <dbl>
    ##  1     1        63.1 Female        16 Carrier           NA baseline   0.111
    ##  2     1        63.1 Female        16 Carrier           NA time_2    NA    
    ##  3     1        63.1 Female        16 Carrier           NA time_4     0.109
    ##  4     1        63.1 Female        16 Carrier           NA time_6     0.105
    ##  5     1        63.1 Female        16 Carrier           NA time_8     0.107
    ##  6     2        65.6 Female        20 Carrier           NA baseline   0.107
    ##  7     2        65.6 Female        20 Carrier           NA time_2     0.109
    ##  8     2        65.6 Female        20 Carrier           NA time_4     0.109
    ##  9     2        65.6 Female        20 Carrier           NA time_6     0.106
    ## 10     2        65.6 Female        20 Carrier           NA time_8     0.107
    ## # ℹ 2,345 more rows

``` r
mci |>
  distinct(id) |>
  nrow()
```

    ## [1] 471

I used an inner join to merge the two datasets by participant ID. This
matches observations with the same participant ID across the two
datasets, while participants who are not present in both datasets are
excluded. So the resulting dataset contains only participants who have
information in both the baseline and amyloid datasets. The final merged
dataset contains 2,355 observations and 8 variables, representing 471
unique participants. Each participant has five observations
corresponding to the five amyloid measurement times.

``` r
write_csv(
  mci,
  "data/mci_merged.csv"
)
```
